version: '3.8'

services:
  zifei-panel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zifei-panel
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      - NODE_ENV=production
    # Removing volume mount temporarily for debugging
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
